### ISSUE TITLE
Please review my usage since it's failing

### ISSUE THREAD

**Issue by kaihendry** [hasnat/docker-volumes-provisioner#1]
Spotted to work at https://github.com/docker/compose/issues/3270#issuecomment-504101249

Still hitting "opening storage failed: lock DB directory: open /prometheus/data/lock: permission denied"

Could you please review my [docker-compose.yml](https://github.com/kaihendry/pingprom/blob/hasnat/docker-compose.yml), especially since I also want grafana also setup.

Thank you!

**Comment by hasnat** [comment]
I think I might have it wrong in example compose file.
Prometheus asks for data directory to be nobody (65534) , grafana states (472)
check pull request on your repo https://github.com/kaihendry/pingprom/pull/3
